### ISSUE TITLE
Support templated forward 

### ISSUE THREAD

**Issue by alexgrip** [picadoh/mockserver-client-csharp#17]
Support using templates when forwarding 

https://www.mock-server.com/mock_server/creating_expectations.html#forward_action

**Comment by alexgrip** [comment]
PR coming

**Comment by picadoh** [comment]
Hi. My apologies for the delay, this project has been stale for some time.

This was implemented in commit 586d548b6efaa5d206dcf67e3fae568a453b941e on top of a bigger to update the repository dependencies, enhance the overall code, add some missing functionality, add proper CI/CD and configure branch rulesets (See also release [2.1.0](https://www.nuget.org/packages/MockServerClientNet/2.1.0)).

Only Mustache and Velocity are supported for now due to some currently known limitations with Javascript templates that prevent testing against the latest version of the server.
